"use client";

import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";

interface AIInsightCardProps {
  insightType: string;
  title: string;
  content: string;
}

const typeConfig: Record<string, { borderColor: string; badgeLabel: string }> = {
  performance: { borderColor: "border-l-violet-500", badgeLabel: "Performance" },
  recommendation: { borderColor: "border-l-blue-500", badgeLabel: "Recommendation" },
  opportunity: { borderColor: "border-l-emerald-500", badgeLabel: "Opportunity" },
  warning: { borderColor: "border-l-amber-500", badgeLabel: "Alert" },
  success: { borderColor: "border-l-emerald-500", badgeLabel: "Healthy" },
  excellence: { borderColor: "border-l-violet-500", badgeLabel: "Excellence" },
  loyalty: { borderColor: "border-l-blue-500", badgeLabel: "Loyalty" },
  growth: { borderColor: "border-l-emerald-500", badgeLabel: "Growth" },
  bottleneck: { borderColor: "border-l-red-500", badgeLabel: "Bottleneck" },
  lag: { borderColor: "border-l-amber-500", badgeLabel: "Delay" },
  strength: { borderColor: "border-l-emerald-500", badgeLabel: "Strength" },
  installation: { borderColor: "border-l-amber-500", badgeLabel: "Installation" },
  trend: { borderColor: "border-l-blue-500", badgeLabel: "Trend" },
  "post-funding": { borderColor: "border-l-emerald-500", badgeLabel: "Post-Funding" },
};

const defaultConfig = { borderColor: "border-l-violet-500", badgeLabel: "Insight" };

export function AIInsightCard({ insightType, title, content }: AIInsightCardProps) {
  const config = typeConfig[insightType] || defaultConfig;

  return (
    <Card
      className={`border-l-4 ${config.borderColor} bg-gradient-to-r from-violet-50/50 to-white shadow-sm relative overflow-hidden`}
    >
      <CardContent className="p-5">
        {/* Header with AI badge */}
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Sparkles className="h-3.5 w-3.5 text-violet-500" />
            <Badge
              variant="secondary"
              className="bg-violet-100 text-violet-700 text-[10px] font-semibold uppercase tracking-wider"
            >
              AI Generated
            </Badge>
          </div>
          <Badge
            variant="outline"
            className="text-[10px] font-medium text-muted-foreground"
          >
            {config.badgeLabel}
          </Badge>
        </div>

        {/* Content */}
        <p className="text-sm font-semibold text-gray-900">{title}</p>
        <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
          {content}
        </p>

        {/* Footer */}
        <p className="mt-3 text-[10px] text-muted-foreground/60">
          Generated by Claude
        </p>
      </CardContent>
    </Card>
  );
}
